"""empty message

Revision ID: 05f03f15a06d
Revises: c337c92936d1
Create Date: 2021-08-30 00:10:02.229102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05f03f15a06d'
down_revision = 'c337c92936d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coupon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coupon_code', sa.String(length=64), nullable=True),
    sa.Column('coupon_type', sa.String(length=64), nullable=True),
    sa.Column('coupon_discount_percentage', sa.Integer(), nullable=True),
    sa.Column('coupon_hands', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coupon_code')
    )
    op.create_table('coupon_use_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('coupon_code', sa.String(length=128), nullable=False),
    sa.Column('coupon_type', sa.String(length=64), nullable=False),
    sa.Column('coupon_discount_percentage', sa.Integer(), nullable=True),
    sa.Column('coupon_hands_given', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('coupons')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coupons',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('coupon_code', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('coupon_type', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('coupon_discount_percentage', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('coupon_hands_given', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='coupons_pkey')
    )
    op.drop_table('coupon_use_history')
    op.drop_table('coupon')
    # ### end Alembic commands ###
